# Generated by Django 4.0.4 on 2022-05-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Libros',
        ),
    ]
